### ISSUE TITLE
how this library different

### ISSUE THREAD

**Issue by iBasit** [OasisDigital/angular2-firebase#2]
How is this library different to what they already have - https://www.youtube.com/watch?v=RD0xYicNcaY

**Comment by kylecordes** [comment]
I don't know if the Firebase team has released their A2 solution yet. As of that conference talk, they had some initial demo code they shared, if I understand right. Their code tool the approach of providing a Firebase URL in your component code, then using a pipe to subscribe to it. For the work I have underway (that this library came from), I wanted to manage Firebase from my component code, transform and process it in various ways, then only using the async pipe from my template.

**Comment by iBasit** [comment]
They said, it should work out of box and Angular2 is converting to firebase initial supported code.

The reason they had angularfire, is because it was hard to update angular1 scopes async with firebase, but on angular2 it work out of box. 

anyway, thanks for the responce

**Comment by kylecordes** [comment]
The thing that works out of the box: zones automatically captures the fact that something changed, and will trigger change detection. But that is actually the least of the things you need to deal with, this library I'm working on is an attempt to ease more aspects of using firebase with Angular 2. However, it will be great if the firebase team releases a comprehensive toolkit which makes mine unnecessary.

**Comment by kylecordes** [comment]
I've also added a bit of text to the readme file to explain what is different about this library versus the official one. There's a good chance when there's is very complete and polished I will abandon this one and use it; but so far there are things I like better about this library, notably that it takes a lighter touch and leaves more to the application developer to mostly just use the Firebase API.
