### ISSUE TITLE
Cannot react to firebase latest change after firebase record added or deleted.

### ISSUE THREAD

**Issue by davidrensh** [OasisDigital/angular2-firebase#5]
I love this lib so much. But it cannot dynamically refresh data  after firebase record added/canged or deleted.

Is this a by design feature?

**Comment by davidrensh** [comment]
Sorry, my bad, it's doable.

**Comment by kylecordes** [comment]
Yes, as you found the dynamic refresh is just ridiculously easy using typescript, and observables. However, it is also a little bit hard to discover. I plan on publishing a complete example application to accompany this library, showing how to use it. I have another project coming up where I will be using this library, that is when I will make a lot more progress.

**Comment by davidrensh** [comment]
Your contribution save NG2 firebase developers tons of time. 
We are very appreciate your effort !
I added one small function and fixed some issues to adapt to new rxjs and array issue. You may knew it longtime ago. But I leave here in case.
`export function existFirebaseChild(ref: FirebaseQuery): Observable<boolean> {
    return Observable.create(function (observer: any) {
        function value(snapshot: FirebaseDataSnapshot) {
            observer.next(snapshot.exists());
        }
        ref.once('value', value);
        return function () {
            ref.off('value', value);
        }
    });
}`

To use this child exist function:

```
        let oexist = existFirebaseChild(usersRef.child("stores").child(this.selectedStore));
        oexist.subscribe(res => {
            if (res) {
                this.cardexistinstore = res;
            }
        }
        );
```

```
For first element issue in array:
        function child_changed(snapshot: FirebaseDataSnapshot) {
            let key = snapshot.key();
            let child = snapshot.val();
            // TODO replace object rather than mutate it?
            let x = arr.filter((y) => y[keyFieldName] === key);
            if (x) {
                for (var k in child) x[k] = child[k];
            }
            observer.next(arr.slice()); // Safe copy
        }

        function child_removed(snapshot: FirebaseDataSnapshot) {
            let key = snapshot.key();
            let child = snapshot.val();
            let x = arr.filter((y) => y[keyFieldName] === key);
            var xarr: string[] = [];
            if (x) {
                arr.forEach(function (item) {
                    xarr.push(item[keyFieldName]);
                });
                arr.splice(xarr.indexOf(x[0][keyFieldName]), 1);
            }
            observer.next(arr.slice()); // Safe copy

        }

        function child_moved(snapshot: FirebaseDataSnapshot, prevChildKey: string) {
            let key = snapshot.key();
            let child = snapshot.val();
            child[keyFieldName] = key;
            // Remove from old slot
            let x = arr.filter((y) => y[keyFieldName] === key);
            if (x) {
                arr.splice(arr.indexOf(x), 1);
            }
            // Add in new slot
            let prevEntry = arr.filter((y) => y[keyFieldName] === prevChildKey);
            if (prevEntry) {
                arr.splice(arr.indexOf(prevEntry) + 1, 0, child);
            } else {
                arr.splice(0, 0, child);
            }
            observer.next(arr.slice()); // Safe copy
        }
```

**Comment by kylecordes** [comment]
Thank you, when I turned my attention back to this project I will compare what you have pasted above with what is already in the software. I already know about a couple of problems to fix, I will try to fix all of the problems next time I work on it.
