### ISSUE TITLE
Type 'Observable<any[]>' is not assignable to type 'Observable<any[]>'

### ISSUE THREAD

**Issue by seangwright** [OasisDigital/angular2-firebase#6]
Here is my code

```
import { Component } from '@angular/core';
import { Observable } from 'rxjs/Observable';

import * as Firebase from 'firebase';
import { observableFirebaseArray, observableFirebaseObject } from 'angular2-firebase';

@Component({
  moduleId: module.id,
  selector: 'ng2-firebase-app',
  templateUrl: 'ng2-firebase.component.html',
  styleUrls: ['ng2-firebase.component.css']
})
export class Ng2FirebaseAppComponent {
  private _firebaseUrl: string = 'https://myfirebaseurl.firebaseio.com/';

  public data: Observable<any[]>;
  public title: string = 'ng2-firebase works!';

  constructor() {
    this.data = observableFirebaseArray<any>(new Firebase(this._firebaseUrl)
      .child("data")
      .limitToFirst(6));
  }
}
```

Here is my error when running `ng serve` from the angular-cli

```
 Type 'Observable<any[]>' is not assignable to type 'Observable<any[]>'.
  Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```

VS Code also displays the error at this line `this.data = observableFirebaseArray<any>`

I have my ambient typings and npm packages all installed. If I comment out the line that generates the `FirebaseQuery` everything works fine.

I see this project has `"rxjs": "5.0.0-beta.2"`, and the current version of the angular cli (version `0.0.39`) creates new projects requiring `"rxjs": "5.0.0-beta.6"` - is this possibly the cause?

**Comment by kylecordes** [comment]
Yes, the Angular team rearranged things considerably with the release candidates. I'm working on a change now to bring this code up-to-date with the current stuff. Keep in mind it just came out a week ago and I just got back from ng-conf :-)

**Comment by kylecordes** [comment]
Simple answer to the problem in your code though: the types don't match. You declared data as  `Observable<any[]>`, but then set `this.data = observableFirebaseArray<any>`.  "any" is not the same as any[].

**Comment by seangwright** [comment]
`observableFirebaseArray<any>` returns `Observable<any[]>` according to the source `angular2-firebase\lib\observableFirebase.ts - 44`

```
export function observableFirebaseArray<T>(ref: FirebaseQuery): Observable<T[]> { .. }
```

So my component property type should be correct.

No problem on the timeline for a fix - I am also on my way back from the conference, sitting in the airport trying to mess around with all the cool bleeding edge stuff I saw this week. I figured things would be broken everywhere - just thought I would post this to help others out.

**Comment by kylecordes** [comment]
I've published an update to this library and the accompanying demo:

https://github.com/OasisDigital/angular2-firebase-demo

I believe it will address your issue, by updating the relevant underlying libraries.  Please reopen if there is still such a problem to be found.

**Comment by Mahadih534** [comment]
if you want to fix it then just change the following line 
import { Observable} from 'rxjs/observable'   to    import { Observable} from 'rxjs'     
:) :) :100:

**Comment by mtycholaz** [comment]
> if you want to fix it then just change the following line
> import { Observable} from 'rxjs/observable' to import { Observable} from 'rxjs'
> :) :) 💯

I had to do this too. We're looking to update rxjs to the latest version and my hope is that we'll be able to revert this.

**Comment by kylecordes** [comment]
@Mahadih534 @mtycholaz I actually haven't used this code in a year or more; here all of our projects have moved to the official angularfire2 library. (BTW, there is also a new RxFire library, very interesting, and a little more similar to this old library.)  I wasn't aware anyone else was still using this code.  :-)

Could you do a PR to make this compatibility update change?
