### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by NathanWalker** [OasisDigital/angular2-firebase#7]
Curious if this is still being maintained?
I noticed it had not been updated for a bit... at least to rc.4... and looks to be very promising when wanting to use observables with firebase.

**Comment by kylecordes** [comment]
Hello, thanks for your interest!

The project started with one key purpose: To enable using Firebase with A2, before there was any official project from the Google Firebase and A2 teams to do so. That purpose is **now obsolete** - the official angularfire2 project is now much more featureful than this thing.

However, this project still has a lesser, remaining purpose: to experiment with different variations of how an A2-Firebase link much work, to do things differently from the official library and see what might be learned by doing so.

So: yes, I've been occasionally maintaining the project, we have a couple of projects internally using it. I expect it will continue to get minor updates to keep up with A2 versions from time to time, and perhaps a few features also. But if you're looking for the mainstream A2-firebase solution, take a look over at:

https://github.com/angular/angularfire2
